{% set data = load_setup_py_data() %}

package:
  name: q2-composition
  version: {{ data.get('version') }}

source:
  path: ../..

build:
  script: python setup.py install

requirements:
  build:
    - python 3.5*
    - setuptools
    - scikit-bio
    - bokeh
    - biom-format >=2.1.5,<2.2.0
    - scipy
    - qiime2 2017.3.*
    - q2-types 2017.3.*

  run:
    - python 3.5*
    - setuptools
    - scikit-bio
    - bokeh
    - biom-format >=2.1.5,<2.2.0
    - scipy
    - qiime2 2017.3.*
    - q2-types 2017.3.*

test:
  imports:
    - q2_composition
    - qiime2.plugins.composition

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
